name: deploy_backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

env:
  AZURE_FUNCTIONAPP_NAME: 'jacobdaleresume'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend'
  PYTHON_VERSION: '3.12'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Still useful for other az CLI work

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Resolve dependencies with pip
      working-directory: ./backend/api
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"

    - name: Run unit tests
      working-directory: ./backend
      run: |
        pip install pytest
        pytest tests/

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
