name: deploy_backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

env:
  AZURE_FUNCTIONAPP_NAME: 'pyresumecounter'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend'
  PYTHON_VERSION: '3.12'
  AZURE_FUNCTION_URL: ${{ secrets.AZURE_FUNCTION_URL }}
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Resolve dependencies with pip
        working-directory: ./backend/api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Install test deps and run debug + test
        working-directory: ./backend
        run: |
          pip install pytest requests
          
          echo "Checking test folder..."
          ls -la tests
          
          echo "Showing test_get_resume_counter.py"
          cat tests/test_get_resume_counter.py

          echo "Running pytest..."
          python -m pytest tests/ -v

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true